version: '3.4'

networks:
  gisa-net:
    name: gisa-net
    driver: bridge

services:
  boasauderefund:
    image: ${DOCKER_REGISTRY-}boasauderefund
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:5001"
    depends_on:
      - migration_boasauderefund
      - rabbitmq
    networks:
      - gisa-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  migration_boasauderefund:
    build:
      context: .
      dockerfile: Migrations.Dockerfile
    networks:
      - gisa-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - C:\gisa_data\volumes\rabbitmq\data:/var/lib/rabbitmq/
        - C:\gisa_data\volumes\rabbitmq\log:/var/log/rabbitmq
    networks:
      - gisa-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure